# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Kronik' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kronik
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Charts'
  pod 'Braintree'
  pod 'BraintreeDropIn'
  pod 'Braintree/DataCollector'
  pod 'FloatingPanel'
  #pod 'PayPalCheckout'
  
  
end
